import type Database from 'better-sqlite3'

const statements = [
  `CREATE TABLE IF NOT EXISTS stations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    city TEXT,
    postal_code TEXT,
    phone TEXT,
    email TEXT,
    federal_state TEXT DEFAULT 'BW',
    active INTEGER DEFAULT 1,
    created_at TEXT,
    updated_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS work_areas (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    name TEXT NOT NULL,
    short_code TEXT,
    color TEXT,
    description TEXT,
    active INTEGER DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    name TEXT,
    description TEXT,
    permissions_json TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT,
    email TEXT,
    password_hash TEXT,
    display_name TEXT,
    role_id TEXT,
    active INTEGER DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (role_id) REFERENCES roles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS employees (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    birthday TEXT,
    role TEXT,
    employment_type TEXT,
    hourly_wage REAL,
    monthly_salary REAL,
    weekly_hours REAL,
    monthly_hours REAL,
    vacation_days_total REAL,
    vacation_days_used REAL,
    color TEXT,
    status TEXT DEFAULT 'active',
    cash_register_card_number TEXT,
    terminal_enabled INTEGER DEFAULT 1,
    time_tracking_enabled INTEGER DEFAULT 1,
    start_date TEXT,
    end_date TEXT,
    notes TEXT,
    active INTEGER DEFAULT 1,
    employee_access_token TEXT,
    employee_access_enabled INTEGER DEFAULT 1,
    employee_access_created_at TEXT,
    employee_access_last_used_at TEXT,
    preferred_shift_types_json TEXT DEFAULT '[]',
    preferred_work_days_json TEXT DEFAULT '[]',
    not_preferred_work_days_json TEXT DEFAULT '[]',
    can_work_weekends INTEGER DEFAULT 1,
    can_work_holidays INTEGER DEFAULT 1,
    max_preferred_days_per_week INTEGER,
    max_weekly_hours REAL,
    planning_notes TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS employee_work_areas (
    id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    work_area_id TEXT NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (work_area_id) REFERENCES work_areas(id)
  )`,
  `CREATE TABLE IF NOT EXISTS shifts (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT,
    work_area_id TEXT NOT NULL,
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    break_minutes INTEGER DEFAULT 0,
    shift_type TEXT,
    title TEXT,
    note TEXT,
    color TEXT,
    status TEXT DEFAULT 'draft',
    published INTEGER DEFAULT 0,
    conflict INTEGER DEFAULT 0,
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    import_source TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (work_area_id) REFERENCES work_areas(id)
  )`,
  `CREATE TABLE IF NOT EXISTS absences (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    type TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    half_day INTEGER DEFAULT 0,
    status TEXT DEFAULT 'requested',
    comment TEXT,
    requested_at TEXT,
    approved_by TEXT,
    approved_at TEXT,
    rejected_reason TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS vacation_blocks (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    title TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    description TEXT,
    work_area_ids_json TEXT,
    active INTEGER DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    work_area_id TEXT,
    assigned_type TEXT DEFAULT 'all',
    assigned_employee_id TEXT,
    assigned_role TEXT,
    recurrence_type TEXT,
    start_date TEXT,
    end_date TEXT,
    weekdays_json TEXT,
    month_day INTEGER,
    start_time TEXT,
    end_time TEXT,
    confirm_required INTEGER DEFAULT 0,
    control_required INTEGER DEFAULT 0,
    mandatory INTEGER DEFAULT 0,
    priority TEXT DEFAULT 'normal',
    active INTEGER DEFAULT 1,
    icon TEXT,
    created_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS task_logs (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    employee_id TEXT,
    date TEXT NOT NULL,
    status TEXT,
    confirmed_at TEXT,
    confirmed_by TEXT,
    controlled_at TEXT,
    controlled_by TEXT,
    control_result TEXT,
    comment TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(id)
  )`,
  `CREATE TABLE IF NOT EXISTS time_entries (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    shift_id TEXT,
    start_at TEXT NOT NULL,
    end_at TEXT,
    break_minutes INTEGER DEFAULT 0,
    status TEXT DEFAULT 'running',
    source TEXT DEFAULT 'manual',
    started_by TEXT,
    ended_by TEXT,
    start_note TEXT,
    end_note TEXT,
    approval_status TEXT,
    approved_by TEXT,
    approved_at TEXT,
    rejected_by TEXT,
    rejected_at TEXT,
    rejection_reason TEXT,
    correction_note TEXT,
    payroll_relevant INTEGER DEFAULT 0,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS shift_close_checklists (
    id TEXT PRIMARY KEY,
    time_entry_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    fridge_fronted INTEGER DEFAULT 0,
    drinks_filled INTEGER DEFAULT 0,
    cigarettes_filled INTEGER DEFAULT 0,
    shelves_filled INTEGER DEFAULT 0,
    trash_emptied INTEGER DEFAULT 0,
    counter_clean INTEGER DEFAULT 0,
    coffee_area_clean INTEGER DEFAULT 0,
    outside_checked INTEGER DEFAULT 0,
    incidents_noted INTEGER DEFAULT 0,
    handover_possible INTEGER DEFAULT 0,
    closing_ready INTEGER DEFAULT 0,
    everything_ok INTEGER DEFAULT 0,
    incident_note TEXT,
    completed_at TEXT,
    created_at TEXT,
    FOREIGN KEY (time_entry_id) REFERENCES time_entries(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS card_entry_events (
    id TEXT PRIMARY KEY,
    card_number TEXT NOT NULL,
    employee_id TEXT,
    station_id TEXT NOT NULL,
    action_type TEXT,
    entered_at TEXT,
    result TEXT,
    message TEXT,
    created_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
]

export function runSchema(db: Database.Database) {
  for (const sql of statements) {
    db.exec(sql)
  }
}
