import type Database from 'better-sqlite3'

const statements = [
  `CREATE TABLE IF NOT EXISTS stations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    brand TEXT,
    address TEXT,
    street TEXT,
    house_number TEXT,
    city TEXT,
    postal_code TEXT,
    phone TEXT,
    email TEXT,
    contact_person TEXT,
    notes TEXT,
    standard_work_times_json TEXT,
    federal_state TEXT DEFAULT 'BW',
    active INTEGER DEFAULT 1,
    archived_at TEXT,
    deleted_at TEXT,
    created_at TEXT,
    updated_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS station_shift_close_checklist_defs (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    checklist_type TEXT NOT NULL,
    item_key TEXT NOT NULL,
    label TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    answer_mode TEXT NOT NULL DEFAULT 'yes_no',
    group_id TEXT,
    group_label TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id) ON DELETE CASCADE,
    UNIQUE (station_id, checklist_type, item_key)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_ssccd_station_type_active ON station_shift_close_checklist_defs(station_id, checklist_type, active, sort_order)`,
  `CREATE TABLE IF NOT EXISTS work_areas (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    name TEXT NOT NULL,
    short_code TEXT,
    color TEXT,
    description TEXT,
    active INTEGER DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS roles (
    id TEXT PRIMARY KEY,
    name TEXT,
    description TEXT,
    permissions_json TEXT,
    role_key TEXT,
    role_label TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT,
    email TEXT,
    password_hash TEXT,
    display_name TEXT,
    role_id TEXT,
    global_admin INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1,
    last_login_at TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (role_id) REFERENCES roles(id)
  )`,
  `CREATE TABLE IF NOT EXISTS user_station_access (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    role TEXT NOT NULL,
    permissions_json TEXT NOT NULL DEFAULT '{}',
    active INTEGER DEFAULT 1,
    created_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS user_audit_log (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    action TEXT NOT NULL,
    target_user_id TEXT,
    station_id TEXT,
    details_json TEXT,
    created_at TEXT NOT NULL,
    created_by TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_user_audit_log_created ON user_audit_log(created_at)`,
  `CREATE TABLE IF NOT EXISTS employees (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    salutation TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    display_name TEXT NOT NULL,
    short_name TEXT,
    email TEXT,
    phone TEXT,
    mobile_phone TEXT,
    landline_phone TEXT,
    birthday TEXT,
    personnel_number TEXT,
    role TEXT,
    employment_role TEXT,
    employment_type TEXT,
    hourly_wage REAL,
    monthly_salary REAL,
    weekly_hours REAL,
    monthly_hours REAL,
    vacation_days_total REAL,
    vacation_days_used REAL,
    color TEXT,
    status TEXT DEFAULT 'active',
    cash_register_card_number TEXT,
    terminal_enabled INTEGER DEFAULT 1,
    time_tracking_enabled INTEGER DEFAULT 1,
    pin_hash TEXT,
    time_tracking_mode TEXT DEFAULT 'station_default',
    break_mode TEXT DEFAULT 'station_default',
    mobile_punch_mode TEXT DEFAULT 'station_default',
    check_in_mode TEXT DEFAULT 'station_default',
    check_out_mode TEXT DEFAULT 'station_default',
    employee_app_enabled INTEGER DEFAULT 1,
    pay_type TEXT DEFAULT 'hourly',
    max_hours_per_month REAL,
    work_days_json TEXT DEFAULT '["mo","di","mi","do","fr"]',
    manko_money REAL,
    vl_amount REAL,
    hide_in_payroll INTEGER DEFAULT 0,
    overtime_enabled INTEGER DEFAULT 0,
    overtime_start_value REAL,
    overtime_start_date TEXT,
    overtime_current_value REAL,
    overtime_auto_calculate INTEGER DEFAULT 0,
    overtime_include_in_reports INTEGER DEFAULT 1,
    iban TEXT,
    bic TEXT,
    account_holder TEXT,
    vacation_start_enabled INTEGER DEFAULT 0,
    vacation_start_value REAL,
    vacation_start_date TEXT,
    annual_vacation_days REAL,
    vacation_hours_per_day REAL,
    vacation_auto_average_13_weeks INTEGER DEFAULT 0,
    first_break_value REAL,
    first_break_after_hours REAL,
    second_break_value REAL,
    second_break_after_hours REAL,
    use_station_break_settings INTEGER DEFAULT 1,
    own_break_rule_enabled INTEGER DEFAULT 0,
    surcharge_mode TEXT DEFAULT 'none',
    night_surcharge_percent REAL,
    night_surcharge_start TEXT,
    night_surcharge_end TEXT,
    night_surcharge_after_two_hours INTEGER DEFAULT 0,
    saturday_surcharge_percent REAL,
    sunday_surcharge_percent REAL,
    holiday_surcharge_percent REAL,
    special_holiday_surcharge_percent REAL,
    night_0_4_surcharge_percent REAL,
    night_0_4_after_sunday_percent REAL,
    night_0_4_after_holiday_percent REAL,
    night_0_4_after_special_holiday_percent REAL,
    surcharge_calculation_mode TEXT DEFAULT 'higher',
    hide_contact_in_address_book INTEGER DEFAULT 0,
    show_only_first_name_in_employee_app INTEGER DEFAULT 0,
    visible_in_team_schedule INTEGER DEFAULT 1,
    phone_visible_to_team INTEGER DEFAULT 1,
    email_visible_to_team INTEGER DEFAULT 1,
    start_date TEXT,
    end_date TEXT,
    notes TEXT,
    active INTEGER DEFAULT 1,
    employee_access_token TEXT,
    employee_access_enabled INTEGER DEFAULT 1,
    employee_access_created_at TEXT,
    employee_access_last_used_at TEXT,
    preferred_shift_types_json TEXT DEFAULT '[]',
    preferred_work_days_json TEXT DEFAULT '[]',
    not_preferred_work_days_json TEXT DEFAULT '[]',
    can_work_weekends INTEGER DEFAULT 1,
    can_work_holidays INTEGER DEFAULT 1,
    max_preferred_days_per_week INTEGER,
    max_weekly_hours REAL,
    planning_notes TEXT,
    created_at TEXT,
    updated_at TEXT,
    deleted_at TEXT,
    deleted_by TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS employee_work_areas (
    id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    station_id TEXT,
    work_area_id TEXT NOT NULL,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (work_area_id) REFERENCES work_areas(id)
  )`,
  `CREATE TABLE IF NOT EXISTS employee_app_devices (
    id TEXT PRIMARY KEY,
    employee_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    device_label TEXT,
    user_agent TEXT,
    platform TEXT,
    last_ip TEXT,
    first_seen_at TEXT,
    last_seen_at TEXT,
    is_active INTEGER DEFAULT 1,
    revoked_at TEXT,
    revoked_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS shifts (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT,
    work_area_id TEXT NOT NULL,
    date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    break_minutes INTEGER DEFAULT 0,
    shift_type TEXT,
    title TEXT,
    note TEXT,
    color TEXT,
    status TEXT DEFAULT 'draft',
    published INTEGER DEFAULT 0,
    conflict INTEGER DEFAULT 0,
    created_by TEXT,
    updated_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    import_source TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (work_area_id) REFERENCES work_areas(id)
  )`,
  `CREATE TABLE IF NOT EXISTS absences (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    type TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    half_day INTEGER DEFAULT 0,
    status TEXT DEFAULT 'requested',
    comment TEXT,
    requested_at TEXT,
    approved_by TEXT,
    approved_at TEXT,
    rejected_by TEXT,
    rejected_at TEXT,
    rejected_reason TEXT,
    paid INTEGER DEFAULT 0,
    counts_against_vacation INTEGER DEFAULT 0,
    paid_hours_per_day REAL DEFAULT 0,
    paid_hours_total REAL DEFAULT 0,
    absence_days REAL DEFAULT 0,
    certificate_source TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS absence_attachments (
    id TEXT PRIMARY KEY,
    absence_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_mime_type TEXT NOT NULL,
    file_path TEXT NOT NULL,
    uploaded_at TEXT NOT NULL,
    uploaded_by TEXT,
    source TEXT,
    FOREIGN KEY (absence_id) REFERENCES absences(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_absence_attachments_absence ON absence_attachments(absence_id)`,
  `CREATE TABLE IF NOT EXISTS vacation_blocks (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    title TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    description TEXT,
    work_area_ids_json TEXT,
    active INTEGER DEFAULT 1,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    work_area_id TEXT,
    assigned_type TEXT DEFAULT 'all',
    assigned_employee_id TEXT,
    assigned_role TEXT,
    recurrence_type TEXT,
    start_date TEXT,
    end_date TEXT,
    weekdays_json TEXT,
    month_day INTEGER,
    start_time TEXT,
    end_time TEXT,
    confirm_required INTEGER DEFAULT 0,
    control_required INTEGER DEFAULT 0,
    mandatory INTEGER DEFAULT 0,
    priority TEXT DEFAULT 'normal',
    active INTEGER DEFAULT 1,
    icon TEXT,
    created_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    task_kind TEXT DEFAULT 'standard',
    employee_self_service INTEGER DEFAULT 0,
    tablet_station_board INTEGER DEFAULT 0,
    assigned_shift_type TEXT,
    required_for_shift_close INTEGER DEFAULT 0,
    source_shift_id TEXT,
    weekend_task_template_slug TEXT,
    task_category TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS task_logs (
    id TEXT PRIMARY KEY,
    task_id TEXT NOT NULL,
    employee_id TEXT,
    date TEXT NOT NULL,
    status TEXT,
    confirmed_at TEXT,
    confirmed_by TEXT,
    controlled_at TEXT,
    controlled_by TEXT,
    control_result TEXT,
    comment TEXT,
    created_at TEXT,
    updated_at TEXT,
    station_id TEXT,
    source TEXT,
    confirmed_by_employee_id TEXT,
    not_done_reason TEXT,
    time_entry_id TEXT,
    FOREIGN KEY (task_id) REFERENCES tasks(id)
  )`,
  `CREATE TABLE IF NOT EXISTS shift_close_task_responses (
    id TEXT PRIMARY KEY,
    time_entry_id TEXT NOT NULL,
    task_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    shift_id TEXT,
    outcome TEXT NOT NULL,
    not_done_reason TEXT,
    recorded_at TEXT NOT NULL,
    source TEXT NOT NULL,
    created_at TEXT,
    UNIQUE (time_entry_id, task_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sctr_time_entry ON shift_close_task_responses(time_entry_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sctr_station ON shift_close_task_responses(station_id)`,
  `CREATE TABLE IF NOT EXISTS time_entries (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    shift_id TEXT,
    start_at TEXT NOT NULL,
    end_at TEXT,
    break_minutes INTEGER DEFAULT 0,
    status TEXT DEFAULT 'running',
    source TEXT DEFAULT 'manual',
    started_by TEXT,
    ended_by TEXT,
    start_note TEXT,
    end_note TEXT,
    approval_status TEXT,
    approved_by TEXT,
    approved_at TEXT,
    rejected_by TEXT,
    rejected_at TEXT,
    rejection_reason TEXT,
    correction_note TEXT,
    payroll_relevant INTEGER DEFAULT 0,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS shift_close_checklists (
    id TEXT PRIMARY KEY,
    time_entry_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    fridge_fronted INTEGER DEFAULT 0,
    drinks_filled INTEGER DEFAULT 0,
    cigarettes_filled INTEGER DEFAULT 0,
    shelves_filled INTEGER DEFAULT 0,
    trash_emptied INTEGER DEFAULT 0,
    counter_clean INTEGER DEFAULT 0,
    coffee_area_clean INTEGER DEFAULT 0,
    outside_checked INTEGER DEFAULT 0,
    incidents_noted INTEGER DEFAULT 0,
    handover_possible INTEGER DEFAULT 0,
    closing_ready INTEGER DEFAULT 0,
    everything_ok INTEGER DEFAULT 0,
    incident_note TEXT,
    cash_difference REAL,
    completed_at TEXT,
    created_at TEXT,
    FOREIGN KEY (time_entry_id) REFERENCES time_entries(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE TABLE IF NOT EXISTS shift_close_checklist_runs (
    id TEXT PRIMARY KEY,
    time_entry_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    checklist_type TEXT NOT NULL,
    cash_difference REAL,
    truth_confirmed INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    handover_variant TEXT,
    handover_remark TEXT,
    shift_id TEXT,
    checkout_source TEXT,
    FOREIGN KEY (time_entry_id) REFERENCES time_entries(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_shift_close_cl_runs_te ON shift_close_checklist_runs(time_entry_id)`,
  `CREATE TABLE IF NOT EXISTS shift_close_checklist_items (
    id TEXT PRIMARY KEY,
    checklist_id TEXT NOT NULL,
    time_entry_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    checklist_type TEXT NOT NULL,
    item_key TEXT NOT NULL,
    item_label TEXT NOT NULL,
    answer TEXT NOT NULL,
    reason TEXT,
    created_at TEXT,
    FOREIGN KEY (checklist_id) REFERENCES shift_close_checklist_runs(id) ON DELETE CASCADE,
    FOREIGN KEY (time_entry_id) REFERENCES time_entries(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_shift_close_cl_items_checklist ON shift_close_checklist_items(checklist_id)`,
  `CREATE INDEX IF NOT EXISTS idx_shift_close_cl_items_te ON shift_close_checklist_items(time_entry_id)`,
  `CREATE TABLE IF NOT EXISTS card_entry_events (
    id TEXT PRIMARY KEY,
    card_number TEXT NOT NULL,
    employee_id TEXT,
    station_id TEXT NOT NULL,
    action_type TEXT,
    entered_at TEXT,
    result TEXT,
    message TEXT,
    created_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tuv_reports (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    report_date TEXT,
    status TEXT DEFAULT 'draft',
    created_by TEXT,
    created_by_name TEXT,
    inspector_role TEXT,
    weather_note TEXT,
    general_note TEXT,
    completed_by TEXT,
    completed_by_name TEXT,
    completed_at TEXT,
    confirmed_by TEXT,
    confirmed_by_name TEXT,
    confirmed_at TEXT,
    confirmation_text TEXT,
    signature_data_url TEXT,
    printed_at TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_tuv_reports_station_month_year ON tuv_reports(station_id, month, year)`,
  `CREATE TABLE IF NOT EXISTS tuv_report_items (
    id TEXT PRIMARY KEY,
    report_id TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    category TEXT,
    question TEXT NOT NULL,
    status TEXT,
    note TEXT,
    action_required TEXT,
    responsible TEXT,
    due_date TEXT,
    photo_url TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (report_id) REFERENCES tuv_reports(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_tuv_report_items_report ON tuv_report_items(report_id)`,
  `CREATE TABLE IF NOT EXISTS employee_shift_warnings (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    source_time_entry_id TEXT,
    checklist_key TEXT,
    label TEXT NOT NULL,
    message TEXT,
    severity TEXT DEFAULT 'warning',
    created_by TEXT,
    created_at TEXT,
    acknowledged_at TEXT,
    acknowledged_on_time_entry_id TEXT,
    active INTEGER DEFAULT 1
  )`,
  `CREATE INDEX IF NOT EXISTS idx_employee_shift_warnings_employee_active ON employee_shift_warnings(employee_id, active)`,
  `CREATE TABLE IF NOT EXISTS shift_checklist_review_items (
    id TEXT PRIMARY KEY,
    time_entry_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    station_id TEXT NOT NULL,
    checklist_key TEXT NOT NULL,
    label TEXT NOT NULL,
    employee_checked INTEGER DEFAULT 0,
    review_checked INTEGER DEFAULT 1,
    review_comment TEXT,
    reviewed_by TEXT,
    reviewed_at TEXT,
    created_at TEXT,
    updated_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_shift_checklist_review_time_entry ON shift_checklist_review_items(time_entry_id)`,
  `CREATE TABLE IF NOT EXISTS settings (
    id TEXT PRIMARY KEY,
    station_id TEXT,
    key TEXT NOT NULL,
    value TEXT,
    type TEXT,
    created_at TEXT,
    updated_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS fuel_price_cache (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_station_id TEXT,
    status TEXT,
    is_open INTEGER,
    e5 REAL,
    e10 REAL,
    diesel REAL,
    currency TEXT DEFAULT 'EUR',
    raw_json TEXT,
    fetched_at TEXT,
    last_tankerkoenig_fetch_at TEXT,
    created_at TEXT,
    updated_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_fuel_price_cache_station ON fuel_price_cache(station_id)`,
  `CREATE TABLE IF NOT EXISTS payroll_adjustments (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    employee_id TEXT NOT NULL,
    type TEXT NOT NULL,
    amount REAL NOT NULL,
    date TEXT NOT NULL,
    note TEXT,
    created_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_payroll_adj_station_date ON payroll_adjustments(station_id, date)`,
  `CREATE INDEX IF NOT EXISTS idx_payroll_adj_employee ON payroll_adjustments(employee_id)`,
  `CREATE TABLE IF NOT EXISTS station_tablet_devices (
    id TEXT PRIMARY KEY,
    station_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    tablet_token TEXT NOT NULL UNIQUE,
    is_active INTEGER DEFAULT 1,
    first_seen_at TEXT,
    last_seen_at TEXT,
    last_ip TEXT,
    user_agent TEXT,
    created_by TEXT,
    created_at TEXT,
    updated_at TEXT,
    revoked_at TEXT,
    revoked_by TEXT,
    FOREIGN KEY (station_id) REFERENCES stations(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_station_tablet_devices_station ON station_tablet_devices(station_id)`,
  `CREATE INDEX IF NOT EXISTS idx_station_tablet_devices_token ON station_tablet_devices(tablet_token)`,
]

export function runSchema(db: Database.Database) {
  for (const sql of statements) {
    db.exec(sql)
  }
}
